AppName="GoUpBox"
AppDirectory="/tmp/text_app"
AppUrl="http://www.google.com"
RSyncServer="rsync://cdn.gbooking.ru"
RSyncTarget="ehr"
RSyncPath="/win-x64"
CheckForUpdatesVersionUrl="https://cdn.gbooking.ru/ehr-server/rsync/{OS}/VERSION"

