AppName = "GoUpBox"
AppDirectory = "/tmp/test"
AppUrl = "https://www.google.com"
Platform = "ubuntu.20.04-x64"
CheckForUpdatesVersionUrl = "https://cdn.gbooking.ru/ehr_server_latest_rsync/{{.Platform}}/VERSION"
# RsyncArgs = [ "-avz", "--delete", "rsync://web.gbooking.ru/ehr_server", "/tmp/test" ]
RsyncArgs = [ "-avz", "rsync://web.gbooking.ru/ehr_server", "/tmp/test" ]

