# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Build 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install apt package appindicator
      run: sudo apt install libappindicator3-dev

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18.3

    - name: Install apt package appindicator
      run: sudo apt install -y libgtk-3-dev libappindicator3-dev gir1.2-appindicator3-0.1

    - name: Build Ubuntu
      env:
        GOOS: linux
        GOARCH: amd64
      # https://github.com/getlantern/systray/issues/222
      run: go build -v -tags=legacy_appindicator -o bin/goupbox-linux-amd64

    - uses: actions/upload-artifact@v3
      with:
        name: bin/goupbox-linux-amd64
        path: bin

  build-macOS:
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3

    - name: Build MacOS
      env:
        GOOS: darwin
        GOARCH: amd64
      run: go build -v -o bin/goupbox-macos-amd64

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: go build -v -o bin/goupbox-windows-amd64.exe
